### ISSUE TITLE
Program spits out error.

### ISSUE THREAD

**Issue by QuietusWolfe** [Aida-Enna/NGSChecker#1]
System.Management.ManagementException: Invalid class
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at NGSChecker.Program.Main()

**Comment by Aida-Enna** [comment]
Solved in https://github.com/Aida-Enna/NGSChecker/commit/f47bc34577de90e2c2b825cc27b2c245fc997330. Thank you!
